#pragma once
#define CFG_TUSB_MCU OPT_MCU_NONE
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUD_ENABLED 1
#define CFG_TUH_ENABLED 1
#define CFG_TUD_HID 3
#define CFG_TUD_MSC 1
#define CFG_TUD_HID_EP_BUFSIZE 32
#define CFG_TUH_HID 12
#define CFG_TUH_DEVICE_MAX 4
#define CFG_TUH_ENUMERATION_BUFSIZE 512
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUSB_RHPORT1_MODE (OPT_MODE_HOST | OPT_MODE_FULL_SPEED)

#define TUP_DCD_ENDPOINT_MAX 8
#define CFG_TUD_MSC_EP_BUFSIZE 512
